name: Repo Sync to Gitee
on:
  workflow_dispatch:
  schedule:
    - cron: '5 0 * * *'
env:
  # 仓库名称
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  mirror-to-gitee:
    name: Sync to Gitee
    runs-on: ubuntu-latest

    steps:
      - name: Mirror repo to Gitee
        run: |
          git clone --mirror https://github.com/${{ github.repository }}.git repo.git
          cd repo.git
          git config --local credential.helper '!f() { echo "username=cmontage"; echo "password=${GITEE_PASSWORD}"; }; f'
          git remote add gitee https://gitee.com/cmontage/${{ env.REPO_NAME }}.git
          git push gitee --mirror
        env:
          GITEE_PASSWORD: ${{ secrets.GITEE_PASSWORD }}
